-- Star-Yi Arc 的 PostgreSQL 脚本。按顺序分成四段，执行到哪一段，库里就只有那一段为止的数据。
-- 1. 结构：函数和系统表
-- 2. 角色与权限：角色、权限、角色权限关联
-- 3. 超级管理员：admin 账号，以及它和超级管理员角色的关联
-- 4. 普通用户：user1、user2、user3 及其角色关联
-- 演示公告表放在最后。不用 yi-demo 时可以不执行。
--
-- TINYINT 改为 SMALLINT；DATETIME 改为 TIMESTAMP（对应 LocalDateTime，不带时区）。
-- is_deleted 改为 BOOLEAN，对应 Jimmer BaseEntity.deleted 与 @LogicalDeleted("true")。
-- modified_time 的 ON UPDATE CURRENT_TIMESTAMP 由触发器补上。
-- 主键使用 GENERATED BY DEFAULT AS IDENTITY。下面的插入不写 id，序号从 1 递增，后面的关联才能对上。
-- MySQL 版本在 sql/mysql.sql，本仓库运行使用本文件。

-- ========================
-- 1. 结构
-- 停在这里：只有空表。
-- ========================

CREATE OR REPLACE FUNCTION touch_modified_time()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.modified_time := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TABLE sys_users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL,
    password        VARCHAR(100) NOT NULL,
    nickname        VARCHAR(50),
    email           VARCHAR(100),
    phone           VARCHAR(20),
    status          SMALLINT     NOT NULL DEFAULT 0,
    is_super_admin  SMALLINT     NOT NULL DEFAULT 0,
    last_login_time TIMESTAMP,
    created_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_time   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_time    TIMESTAMP,
    is_deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_email UNIQUE (email),
    CONSTRAINT uk_phone UNIQUE (phone)
);

COMMENT ON TABLE sys_users IS '用户表';
COMMENT ON COLUMN sys_users.id IS '主键ID';
COMMENT ON COLUMN sys_users.username IS '用户名';
COMMENT ON COLUMN sys_users.password IS '密码(加密)';
COMMENT ON COLUMN sys_users.nickname IS '昵称/真实姓名';
COMMENT ON COLUMN sys_users.email IS '邮箱';
COMMENT ON COLUMN sys_users.phone IS '手机号';
COMMENT ON COLUMN sys_users.status IS '状态 0:正常 1:禁用 2:删除';
COMMENT ON COLUMN sys_users.is_super_admin IS '是否超级管理员 0:否 1:是';
COMMENT ON COLUMN sys_users.last_login_time IS '最后登录时间';
COMMENT ON COLUMN sys_users.created_time IS '创建时间';
COMMENT ON COLUMN sys_users.modified_time IS '修改时间';
COMMENT ON COLUMN sys_users.deleted_time IS '删除时间';
COMMENT ON COLUMN sys_users.is_deleted IS '是否删除 false:否 true:是';

CREATE INDEX idx_sys_users_status ON sys_users (status);
CREATE INDEX idx_sys_users_deleted ON sys_users (is_deleted);

CREATE TRIGGER trg_sys_users_modified_time
    BEFORE UPDATE ON sys_users
    FOR EACH ROW
    EXECUTE PROCEDURE touch_modified_time();

CREATE TABLE sys_roles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code     VARCHAR(50)  NOT NULL,
    role_name     VARCHAR(50)  NOT NULL,
    description   VARCHAR(200),
    status        SMALLINT     NOT NULL DEFAULT 0,
    created_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_time  TIMESTAMP,
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_role_code UNIQUE (role_code)
);

COMMENT ON TABLE sys_roles IS '角色表';
COMMENT ON COLUMN sys_roles.id IS '主键ID';
COMMENT ON COLUMN sys_roles.role_code IS '角色编码(如: ADMIN, USER)';
COMMENT ON COLUMN sys_roles.role_name IS '角色名称(如: 管理员, 普通用户)';
COMMENT ON COLUMN sys_roles.description IS '角色描述';
COMMENT ON COLUMN sys_roles.status IS '状态 0:正常 1:禁用 2:删除';
COMMENT ON COLUMN sys_roles.created_time IS '创建时间';
COMMENT ON COLUMN sys_roles.modified_time IS '修改时间';
COMMENT ON COLUMN sys_roles.deleted_time IS '删除时间';
COMMENT ON COLUMN sys_roles.is_deleted IS '是否删除 false:否 true:是';

CREATE INDEX idx_sys_roles_status ON sys_roles (status);
CREATE INDEX idx_sys_roles_deleted ON sys_roles (is_deleted);

CREATE TRIGGER trg_sys_roles_modified_time
    BEFORE UPDATE ON sys_roles
    FOR EACH ROW
    EXECUTE PROCEDURE touch_modified_time();

CREATE TABLE sys_permissions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code  VARCHAR(100) NOT NULL,
    permission_name  VARCHAR(50)  NOT NULL,
    permission_type  SMALLINT     NOT NULL DEFAULT 1,
    parent_id        BIGINT       DEFAULT 0,
    path             VARCHAR(200),
    icon             VARCHAR(50),
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    status           SMALLINT     NOT NULL DEFAULT 0,
    created_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_time     TIMESTAMP,
    is_deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_permission_code UNIQUE (permission_code)
);

COMMENT ON TABLE sys_permissions IS '权限表';
COMMENT ON COLUMN sys_permissions.id IS '主键ID';
COMMENT ON COLUMN sys_permissions.permission_code IS '权限编码(如: user:add, user:delete)';
COMMENT ON COLUMN sys_permissions.permission_name IS '权限名称(如: 用户新增, 用户删除)';
COMMENT ON COLUMN sys_permissions.permission_type IS '权限类型 1:菜单 2:按钮 3:接口';
COMMENT ON COLUMN sys_permissions.parent_id IS '父级权限ID(0表示顶级)';
COMMENT ON COLUMN sys_permissions.path IS '前端路由路径';
COMMENT ON COLUMN sys_permissions.icon IS '图标';
COMMENT ON COLUMN sys_permissions.sort_order IS '排序号';
COMMENT ON COLUMN sys_permissions.status IS '状态 0:正常 1:禁用 2:删除';
COMMENT ON COLUMN sys_permissions.created_time IS '创建时间';
COMMENT ON COLUMN sys_permissions.modified_time IS '修改时间';
COMMENT ON COLUMN sys_permissions.deleted_time IS '删除时间';
COMMENT ON COLUMN sys_permissions.is_deleted IS '是否删除 false:否 true:是';

CREATE INDEX idx_sys_permissions_parent_id ON sys_permissions (parent_id);
CREATE INDEX idx_sys_permissions_status ON sys_permissions (status);
CREATE INDEX idx_sys_permissions_deleted ON sys_permissions (is_deleted);

CREATE TRIGGER trg_sys_permissions_modified_time
    BEFORE UPDATE ON sys_permissions
    FOR EACH ROW
    EXECUTE PROCEDURE touch_modified_time();

CREATE TABLE sys_user_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT    NOT NULL,
    role_id      BIGINT    NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   BIGINT,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES sys_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES sys_roles (id) ON DELETE CASCADE
);

COMMENT ON TABLE sys_user_role IS '用户 - 角色关联表';
COMMENT ON COLUMN sys_user_role.id IS '主键 ID';
COMMENT ON COLUMN sys_user_role.user_id IS '用户 ID';
COMMENT ON COLUMN sys_user_role.role_id IS '角色 ID';
COMMENT ON COLUMN sys_user_role.created_time IS '创建时间';
COMMENT ON COLUMN sys_user_role.created_by IS '创建人 ID(可为空)';

CREATE INDEX idx_sys_user_role_user_id ON sys_user_role (user_id);
CREATE INDEX idx_sys_user_role_role_id ON sys_user_role (role_id);

CREATE TABLE sys_role_permission (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id        BIGINT    NOT NULL,
    permission_id  BIGINT    NOT NULL,
    created_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     BIGINT,
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES sys_roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES sys_permissions (id) ON DELETE CASCADE
);

COMMENT ON TABLE sys_role_permission IS '角色 - 权限关联表';
COMMENT ON COLUMN sys_role_permission.id IS '主键 ID';
COMMENT ON COLUMN sys_role_permission.role_id IS '角色 ID';
COMMENT ON COLUMN sys_role_permission.permission_id IS '权限 ID';
COMMENT ON COLUMN sys_role_permission.created_time IS '创建时间';
COMMENT ON COLUMN sys_role_permission.created_by IS '创建人 ID(可为空)';

CREATE INDEX idx_sys_role_permission_role_id ON sys_role_permission (role_id);
CREATE INDEX idx_sys_role_permission_permission_id ON sys_role_permission (permission_id);

CREATE TABLE sys_login_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT,
    username       VARCHAR(50)  NOT NULL,
    login_type     SMALLINT     NOT NULL DEFAULT 1,
    status         SMALLINT     NOT NULL DEFAULT 0,
    fail_reason    VARCHAR(200),
    ip_address     VARCHAR(50),
    login_location VARCHAR(200),
    browser        VARCHAR(100),
    os             VARCHAR(100),
    user_agent     VARCHAR(500),
    token_value    VARCHAR(64),
    login_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_login_log IS '登录日志表';
COMMENT ON COLUMN sys_login_log.id IS '主键ID';
COMMENT ON COLUMN sys_login_log.user_id IS '用户ID(逻辑关联，无外键；删除用户后仍保留原值)';
COMMENT ON COLUMN sys_login_log.username IS '登录账号(用户名/手机号)';
COMMENT ON COLUMN sys_login_log.login_type IS '操作类型 1:登录 2:登出';
COMMENT ON COLUMN sys_login_log.status IS '状态 0:成功 1:失败';
COMMENT ON COLUMN sys_login_log.fail_reason IS '失败原因';
COMMENT ON COLUMN sys_login_log.ip_address IS '登录IP';
COMMENT ON COLUMN sys_login_log.login_location IS '登录地点';
COMMENT ON COLUMN sys_login_log.browser IS '浏览器';
COMMENT ON COLUMN sys_login_log.os IS '操作系统';
COMMENT ON COLUMN sys_login_log.user_agent IS 'User-Agent';
COMMENT ON COLUMN sys_login_log.token_value IS 'Token标识(脱敏,便于会话追踪)';
COMMENT ON COLUMN sys_login_log.login_time IS '登录/登出时间';

CREATE INDEX idx_sys_login_log_user_id ON sys_login_log (user_id);
CREATE INDEX idx_sys_login_log_username ON sys_login_log (username);
CREATE INDEX idx_sys_login_log_login_time ON sys_login_log (login_time);
CREATE INDEX idx_sys_login_log_status ON sys_login_log (status);
CREATE INDEX idx_sys_login_log_login_type ON sys_login_log (login_type);

-- ========================
-- 2. 角色与权限
-- 停在这里：有表、有角色和权限，没有登录账号。
-- ========================

INSERT INTO sys_roles (role_code, role_name, description, status) VALUES
('SUPER_ADMIN', '超级管理员', '拥有系统所有权限', 0),
('ADMIN', '管理员', '拥有系统管理权限', 0),
('USER', '普通用户', '普通用户权限', 0);

INSERT INTO sys_permissions (permission_code, permission_name, permission_type, parent_id, path, icon, sort_order, status) VALUES
('system', '系统管理', 1, 0, '/system', 'setting', 1, 0),
('user', '用户管理', 1, 0, '/user', 'user', 2, 0),
('role', '角色管理', 1, 0, '/role', 'role', 3, 0),
('permission', '权限管理', 1, 0, '/permission', 'lock', 4, 0),
('system:user', '用户管理', 1, 1, '/system/user', 'user', 1, 0),
('system:role', '角色管理', 1, 1, '/system/role', 'role', 2, 0),
('system:permission', '权限管理', 1, 1, '/system/permission', 'lock', 3, 0),
('system:user:add', '用户新增', 2, 5, NULL, NULL, 1, 0),
('system:user:edit', '用户编辑', 2, 5, NULL, NULL, 2, 0),
('system:user:delete', '用户删除', 2, 5, NULL, NULL, 3, 0),
('system:user:view', '用户查看', 2, 5, NULL, NULL, 4, 0),
('system:role:add', '角色新增', 2, 6, NULL, NULL, 1, 0),
('system:role:edit', '角色编辑', 2, 6, NULL, NULL, 2, 0),
('system:role:delete', '角色删除', 2, 6, NULL, NULL, 3, 0),
('system:role:view', '角色查看', 2, 6, NULL, NULL, 4, 0);

-- created_by 记的是下一段才会插入的 admin，本列没有外键。
INSERT INTO sys_role_permission (role_id, permission_id, created_by) VALUES
(1, 1, 1), (1, 2, 1), (1, 3, 1), (1, 4, 1),
(1, 5, 1), (1, 6, 1), (1, 7, 1),
(1, 8, 1), (1, 9, 1), (1, 10, 1), (1, 11, 1),
(1, 12, 1), (1, 13, 1), (1, 14, 1), (1, 15, 1);

INSERT INTO sys_role_permission (role_id, permission_id, created_by) VALUES
(2, 1, 1), (2, 2, 1), (2, 3, 1),
(2, 5, 1), (2, 6, 1), (2, 7, 1),
(2, 8, 1), (2, 9, 1), (2, 11, 1),
(2, 12, 1), (2, 13, 1), (2, 15, 1);

INSERT INTO sys_role_permission (role_id, permission_id, created_by) VALUES
(3, 2, 1),
(3, 5, 1),
(3, 11, 1);

-- ========================
-- 3. 超级管理员
-- 停在这里：可以用 admin 登录。密码是 123456 的 SHA-256。
-- admin 是第一条用户，id 为 1，对应角色 SUPER_ADMIN（id 为 1）。
-- ========================

INSERT INTO sys_users (username, password, nickname, email, phone, status, is_super_admin) VALUES
('admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', '超级管理员', 'admin@example.com', '13800138000', 0, 1);

INSERT INTO sys_user_role (user_id, role_id, created_by) VALUES
(1, 1, 1);

-- ========================
-- 4. 普通用户
-- 停在这里：样例用户也在。user1、user2 是普通用户，user3 是管理员。
-- ========================

INSERT INTO sys_users (username, password, nickname, email, phone, status, is_super_admin) VALUES
('user1', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', '张三', 'zhangsan@example.com', '13800138001', 0, 0),
('user2', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', '李四', 'lisi@example.com', '13800138002', 0, 0),
('user3', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', '王五', 'wangwu@example.com', '13800138003', 0, 0);

INSERT INTO sys_user_role (user_id, role_id, created_by) VALUES
(2, 3, 1),
(3, 3, 1),
(4, 2, 1);

-- ========================
-- 演示公告
-- yi-demo 的 DemoNotice 使用这张表。不用演示模块时可以不执行。
-- ========================

CREATE TABLE demo_notice (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(128) NOT NULL,
    content       VARCHAR(500),
    pinned        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_time  TIMESTAMP,
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE demo_notice IS '演示公告表';
COMMENT ON COLUMN demo_notice.id IS '主键';
COMMENT ON COLUMN demo_notice.title IS '标题';
COMMENT ON COLUMN demo_notice.content IS '正文';
COMMENT ON COLUMN demo_notice.pinned IS '是否置顶';
COMMENT ON COLUMN demo_notice.created_time IS '创建时间';
COMMENT ON COLUMN demo_notice.modified_time IS '修改时间';
COMMENT ON COLUMN demo_notice.deleted_time IS '删除时间';
COMMENT ON COLUMN demo_notice.is_deleted IS '是否删除 false:否 true:是';

CREATE TRIGGER trg_demo_notice_modified_time
    BEFORE UPDATE ON demo_notice
    FOR EACH ROW
    EXECUTE PROCEDURE touch_modified_time();
